import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {DiscountBanner} from '@/components/discount-banner'
import {SiteFooter} from '@/components/site-footer'
import {SiteHeader} from '@/components/site-header'
import { Toaster } from 'sonner'
import { CartProvider } from "@/contexts/cart-context"
import NextAuthSessionProvider from '@/contexts/session-provider'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}container items-center` }>
         <NextAuthSessionProvider>

         
          <CartProvider>
          
              {children}
              <Toaster richColors position="top-right" />
              
          </CartProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
