/**
 * Placeholder data for development and testing
 * This simulates MongoDB data without actual database connection
 */

import { type Product, type Category,type  DiscountBanner  } from "./schema"

export const mockDiscountBanner: DiscountBanner = {
  _id: "banner_1",
  title: "Spring Sale",
  description: "Get 10% off on all scooters",
  discountPercentage: 10,
  isActive: true,
  startDate: new Date("2024-03-01"),
  endDate: new Date("2024-04-30"),
  createdAt: new Date("2024-02-25"),
  updatedAt: new Date("2024-02-25"),
}


export const mockCategories: Category[] = [
  {
    _id: "cat_1",
    name: " E-Scooters",
    slug: "electric-scooters",
    description: "High-performance electric scooters for urban commuting",
    image: "/images/modern-electric-scooter.png",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "cat_2",
    name: "E-Bikes",
    slug: "commuter-series",
    description: "Perfect for daily commutes and city travel",
    image: "/images/off-road-electric-scooter-terrain.jpg",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "cat_3",
    name: "E-Dirt Bike",
    slug: "performance-series",
    description: "High-speed scooters for thrill seekers",
    image: "/images/Natike.png",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    _id: "cat_4",
    name: "E-crussiers",
    slug: "off-road-series",
    description: "Rugged scooters built for any terrain",
    image: "/images/engwe.webp",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const mockProducts: Product[] = [
  {
    _id: "prod_2",
    name: "Natike",
    slug: "velocity-x1",
    description:
      "Experience unmatched speed and power with the Velocity X1. Built for performance enthusiasts who demand the best.",
    shortDescription: "High-performance scooter reaching 35 mph",
    price: 1499,
    compareAtPrice: 1799,
    images: ["/images/Natike.png", "/images/sport-electric-scooter.jpg"],
    category: "cat_3",
    specifications: {
      maxSpeed: "35 mph",
      range: "35 miles",
      weight: "42 lbs",
      maxLoad: "300 lbs",
      batteryCapacity: "52V 20Ah",
      chargingTime: "7-9 hours",
      motor: "1000W Dual Motor",
    },
    stock: 28,
    sku: "VX1-001",
    isActive: true,
    isFeatured: true,
    tags: ["performance", "high-speed", "dual-motor"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
    createdBy: "admin_1",
  },
  
  
  {
    _id: "prod_3",
    name: "EcoRide Lite",
    slug: "ecoride-lite",
    description: "Affordable and eco-friendly, the EcoRide Lite is perfect for short trips and casual riders.",
    shortDescription: "Budget-friendly option for city travel",
    price: 499,
    compareAtPrice: 599,
    images: ["/images/white-compact-electric-scooter-affordable.jpg", "/images/lightweight-electric-scooter.png"],
    category: "cat_1",
    specifications: {
      maxSpeed: "18 mph",
      range: "20 miles",
      weight: "26 lbs",
      maxLoad: "220 lbs",
      batteryCapacity: "36V 10Ah",
      chargingTime: "4-5 hours",
      motor: "350W Brushless",
    },
    stock: 67,
    sku: "ERL-001",
    isActive: true,
    isFeatured: false,
    tags: ["budget", "lightweight", "eco-friendly"],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
    createdBy: "admin_1",
  },
  {
    _id: "prod_1",
    name: "Urban Glide Pro",
    slug: "urban-glide-pro",
    description:
      "The Urban Glide Pro combines sleek design with powerful performance. Perfect for daily commutes with its long-range battery and smooth ride quality.",
    shortDescription: "Premium commuter scooter with 40-mile range",
    price: 899,
    compareAtPrice: 1099,
    images: ["/images/sleek-black-electric-scooter-urban.jpg", "/images/electric-scooter-side-view.jpg"],
    category: "cat_1",
    specifications: {
      maxSpeed: "25 mph",
      range: "40 miles",
      weight: "35 lbs",
      maxLoad: "265 lbs",
      batteryCapacity: "48V 15Ah",
      chargingTime: "6-8 hours",
      motor: "500W Brushless",
    },
    stock: 45,
    sku: "UGP-001",
    isActive: true,
    isFeatured: true,
    tags: ["commuter", "long-range", "bestseller"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    createdBy: "admin_1",
  },
  {
    _id: "prod_4",
    name: "L6 Pro",
    slug: "trailblazer-max",
    description: "Conquer any terrain with the TrailBlazer Max. Features all-terrain tires and superior suspension.",
    shortDescription: "Off-road beast with all-terrain capability",
    price: 1799,
    compareAtPrice: 2099,
    images: ["/images/l6pro.webp", "/images/all-terrain-electric-scooter.jpg"],
    category: "cat_4",
    specifications: {
      maxSpeed: "30 mph",
      range: "45 miles",
      weight: "55 lbs",
      maxLoad: "330 lbs",
      batteryCapacity: "60V 25Ah",
      chargingTime: "8-10 hours",
      motor: "1200W Dual Motor",
    },
    stock: 15,
    sku: "TBM-001",
    isActive: true,
    isFeatured: true,
    tags: ["off-road", "all-terrain", "heavy-duty"],
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
    createdBy: "admin_1",
  },
  {
    _id: "prod_5",
    name: "L3 pro",
    slug: "city-cruiser",
    description:
      "Navigate city streets with ease. The City Cruiser offers the perfect balance of portability and performance.",
    shortDescription: "Portable and powerful city scooter",
    price: 699,
    compareAtPrice: 849,
    images: ["/images/l3pro.webp", "/images/foldable-electric-scooter.jpg"],
    category: "cat_2",
    specifications: {
      maxSpeed: "22 mph",
      range: "28 miles",
      weight: "30 lbs",
      maxLoad: "250 lbs",
      batteryCapacity: "42V 12Ah",
      chargingTime: "5-6 hours",
      motor: "450W Brushless",
    },
    stock: 52,
    sku: "CC-001",
    isActive: true,
    isFeatured: false,
    tags: ["portable", "foldable", "city"],
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
    createdBy: "admin_1",
  },
  {
    _id: "prod_6",
    name: "J1",
    slug: "thunder-pro",
    description: "Unleash the thunder with this powerhouse scooter. Maximum speed and range for serious riders.",
    shortDescription: "Ultimate performance with 50-mile range",
    price: 1999,
    compareAtPrice: 2399,
    images: ["/images/j1.webp", "/images/high-end-electric-scooter.jpg"],
    category: "cat_3",
    specifications: {
      maxSpeed: "40 mph",
      range: "50 miles",
      weight: "48 lbs",
      maxLoad: "320 lbs",
      batteryCapacity: "60V 30Ah",
      chargingTime: "9-11 hours",
      motor: "1500W Dual Motor",
    },
    stock: 12,
    sku: "TP-001",
    isActive: true,
    isFeatured: true,
    tags: ["premium", "long-range", "high-performance"],
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
    createdBy: "admin_1",
  },
]






export const PLACEHOLDER_PRODUCTS = mockProducts
